export default {
  data: [
    {
      location_id: "189330",
      name: "Holiday Inn Express Manchester - East, an IHG hotel",
      latitude: "53.460297",
      longitude: "-2.162759",
      num_reviews: "766",
      timezone: "Europe/London",
      location_string: "Manchester, Greater Manchester, England",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/21/a0/35/0a/free-parking-is-available.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/21/a0/35/0a/free-parking-is-available.jpg",
            height: "50",
          },
          original: {
            width: "4500",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/21/a0/35/0a/free-parking-is-available.jpg",
            height: "3004",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/21/a0/35/0a/free-parking-is-available.jpg",
            height: "367",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/21/a0/35/0a/free-parking-is-available.jpg",
            height: "167",
          },
        },
        is_blessed: true,
        uploaded_date: "2021-12-16T04:36:57-0500",
        caption: "Free parking is available for guests at our Manchester hotel",
        id: "564147466",
        helpful_votes: "0",
        published_date: "2021-12-16T04:36:57-0500",
        user: null,
      },
      awards: [
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2020",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2020_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2020",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2018",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2018_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2018",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2017",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2017_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2017",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2015",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2015_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2015",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2012",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2012_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2012",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2011",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2011_en_US-0-5.png",
          },
          categories: [],
          display_name: "Certificate of Excellence 2011",
        },
      ],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Manchester Places to Stay",
      raw_ranking: "3.922954797744751",
      ranking_geo: "Manchester",
      ranking_geo_id: "187069",
      ranking_position: "1",
      ranking_denominator: "361",
      ranking_category: "hotel",
      ranking: "#1 Best Value of 361 places to stay in Manchester",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "0.9118697290924157",
      distance_string: null,
      bearing: "southwest",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$67 - $132",
      hotel_class: "3.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: { desktop_contacts: [], mobile_contacts: [] },
      special_offers: { desktop: [], mobile: [] },
      listing_key: "d3e7fcf1-48a1-4167-b8ec-c9710469b2cc",
    },
    {
      location_id: "565992",
      name: "Travelodge Ashton Under Lyne",
      latitude: "53.4802",
      longitude: "-2.124423",
      num_reviews: "499",
      timezone: "Europe/London",
      location_string:
        "Ashton-under-Lyne, Tameside, Greater Manchester, England",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/13/70/a1/db/exterior.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/13/70/a1/db/exterior.jpg",
            height: "50",
          },
          original: {
            width: "1500",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/13/70/a1/db/exterior.jpg",
            height: "1125",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/13/70/a1/db/exterior.jpg",
            height: "412",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/13/70/a1/db/exterior.jpg",
            height: "188",
          },
        },
        is_blessed: true,
        uploaded_date: "2018-06-23T09:44:19-0400",
        caption: "Exterior",
        id: "326148571",
        helpful_votes: "0",
        published_date: "2018-06-23T09:44:19-0400",
        user: null,
      },
      awards: [
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2020",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2020_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2020",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2017",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2017_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2017",
        },
      ],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Manchester Places to Stay",
      raw_ranking: "3.980466365814209",
      ranking_geo: "Ashton-under-Lyne",
      ranking_geo_id: "644360",
      ranking_position: "2",
      ranking_denominator: "361",
      ranking_category: "hotel",
      ranking: "#2 Best Value of 361 places to stay in Manchester",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "1.1835199205059168",
      distance_string: null,
      bearing: "northeast",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$46 - $83",
      hotel_class: "2.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: { desktop_contacts: [], mobile_contacts: [] },
      special_offers: { desktop: [], mobile: [] },
      listing_key: "ada048f4-90d5-4d40-a005-0d85b90d989b",
    },
    {
      location_id: "571144",
      name: "Premier Inn Manchester (Denton) hotel",
      latitude: "53.45569",
      longitude: "-2.134468",
      num_reviews: "792",
      timezone: "Europe/London",
      location_string: "Denton, Tameside, Greater Manchester, England",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/19/71/80/fb/premier-inn-manchester.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/19/71/80/fb/premier-inn-manchester.jpg",
            height: "50",
          },
          original: {
            width: "1280",
            url: "https://media-cdn.tripadvisor.com/media/photo-m/1280/19/71/80/fb/premier-inn-manchester.jpg",
            height: "850",
          },
          large: {
            width: "1024",
            url: "https://media-cdn.tripadvisor.com/media/photo-w/19/71/80/fb/premier-inn-manchester.jpg",
            height: "680",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/19/71/80/fb/premier-inn-manchester.jpg",
            height: "365",
          },
        },
        is_blessed: true,
        uploaded_date: "2019-09-30T10:41:10-0400",
        caption: "Premier Inn Manchester (Denton) hotel exterior",
        id: "426868987",
        helpful_votes: "0",
        published_date: "2019-09-30T10:41:10-0400",
        user: { user_id: null, member_id: "0", type: "user" },
      },
      awards: [
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2021",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2021_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2021",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2020",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2020_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2020",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2019",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2019_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2019",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2018",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2018_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2018",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2017",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2017_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2017",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2016",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2016_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2016",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2015",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2015_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2015",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2014",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2014_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2014",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2013",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2013_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2013",
        },
        {
          award_type: "CERTIFICATE_OF_EXCELLENCE",
          year: "2012",
          images: {
            small:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
            large:
              "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2012_en_US_large-0-5.jpg",
          },
          categories: [],
          display_name: "Certificate of Excellence 2012",
        },
      ],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Manchester Places to Stay",
      raw_ranking: "4.418318748474121",
      ranking_geo: "Denton",
      ranking_geo_id: "1757395",
      ranking_position: "3",
      ranking_denominator: "361",
      ranking_category: "hotel",
      ranking: "#3 Best Value of 361 places to stay in Manchester",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "1.0062142559924507",
      distance_string: null,
      bearing: "southeast",
      rating: "4.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$49 - $94",
      hotel_class: "3.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [
          {
            value:
              "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=571144&from=api&area=&slot=1&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=CLM&tm=232026447&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkWOWX1Xm_z7xxTZgV0sjFuyw_qHNrrXj6ihIUEvA0VM-eErGF6zhzZtFbp55dE_2xQ&bapid=1&cs=1863fe67923f762851616de364cf9be25",
            label: "Hotel website",
            type: "url",
          },
        ],
      },
      special_offers: { desktop: [], mobile: [] },
      listing_key: "31f46c57-67f4-49e7-82f9-5c08d9f64665",
    },
    {
      location_id: "13519361",
      name: "Holiday Guest House",
      latitude: "53.47945",
      longitude: "-2.14642",
      num_reviews: "2",
      timezone: "Europe/London",
      location_string: "Manchester, Greater Manchester, England",
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Manchester Places to Stay",
      raw_ranking: "3.0525331497192383",
      ranking_geo: "Manchester",
      ranking_geo_id: "187069",
      ranking_position: "4",
      ranking_denominator: "361",
      ranking_category: "bb",
      ranking: "#4 Best Value of 361 places to stay in Manchester",
      subcategory_type: "guest_house",
      subcategory_type_label: "Guest house",
      distance: "0.7488006795279348",
      distance_string: null,
      bearing: "north",
      rating: "5.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: { desktop_contacts: [], mobile_contacts: [] },
      special_offers: { desktop: [], mobile: [] },
      listing_key: "9b10ea9a-aecf-44fc-b88a-15019729de56",
    },
    {
      location_id: "12462690",
      name: "B&B 51 Cherry Avenue",
      latitude: "53.46926",
      longitude: "-2.17067",
      num_reviews: "4",
      timezone: "Europe/London",
      location_string: "Manchester, Greater Manchester, England",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/1b/0b/d6/b5/photoofthewholeroom.jpg",
            height: "137",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/1b/0b/d6/b5/photoofthewholeroom.jpg",
            height: "50",
          },
          original: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1b/0b/d6/b5/photoofthewholeroom.jpg",
            height: "460",
          },
          large: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1b/0b/d6/b5/photoofthewholeroom.jpg",
            height: "460",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/1b/0b/d6/b5/photoofthewholeroom.jpg",
            height: "301",
          },
        },
        is_blessed: true,
        uploaded_date: "2020-02-29T22:23:43-0500",
        caption: "Photo of the whole room",
        id: "453760693",
        helpful_votes: "0",
        published_date: "2020-02-29T22:23:43-0500",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Manchester Places to Stay",
      raw_ranking: "3.034806966781616",
      ranking_geo: "Manchester",
      ranking_geo_id: "187069",
      ranking_position: "5",
      ranking_denominator: "361",
      ranking_category: "bb",
      ranking: "#5 Best Value of 361 places to stay in Manchester",
      subcategory_type: "bed_and_breakfast",
      subcategory_type_label: "Bed and Breakfast",
      distance: "1.0328185383974573",
      distance_string: null,
      bearing: "west",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: { desktop_contacts: [], mobile_contacts: [] },
      special_offers: { desktop: [], mobile: [] },
      listing_key: "b045a0a5-f352-4c91-9ef6-4cbe88eef640",
    },
    {
      location_id: "15239671",
      name: "Fit-4-Life BnB",
      latitude: "53.45621",
      longitude: "-2.15955",
      num_reviews: "0",
      timezone: "Europe/London",
      location_string: "Greater Manchester, England",
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Manchester Places to Stay",
      ranking_position: "6",
      ranking_denominator: "361",
      ranking: "#6 Best Value of 361 places to stay in Manchester",
      distance: "1.0335434261541114",
      distance_string: null,
      bearing: "southwest",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: { desktop_contacts: [], mobile_contacts: [] },
      special_offers: { desktop: [], mobile: [] },
      listing_key: "ea2644e4-696c-41d0-ac9b-b1e51eb52c22",
    },
    {
      location_id: "187069",
      ad_position: "inline1",
      ad_size: "8X8",
      doubleclick_zone: "eu.uk.england.greater_manchester.manchester",
      ancestors: [
        {
          subcategory: [{ key: "county", name: "County" }],
          name: "Greater Manchester",
          abbrv: null,
          location_id: "187052",
        },
        {
          subcategory: [{ key: "nation", name: "Nation" }],
          name: "England",
          abbrv: null,
          location_id: "186217",
        },
        {
          subcategory: [{ key: "country", name: "Country" }],
          name: "United Kingdom",
          abbrv: "UK",
          location_id: "186216",
        },
      ],
      detail: "0",
      page_type: "hotels",
      mob_ptype: "app_hotels",
    },
    {
      location_id: "12574647",
      name: "Carfax House",
      latitude: "53.464478",
      longitude: "-2.170514",
      num_reviews: "0",
      timezone: "Europe/London",
      location_string: "Manchester, Greater Manchester, England",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/23/4f/84/2a/caption.jpg",
            height: "137",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/23/4f/84/2a/caption.jpg",
            height: "50",
          },
          original: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/23/4f/84/2a/caption.jpg",
            height: "460",
          },
          large: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/23/4f/84/2a/caption.jpg",
            height: "460",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/23/4f/84/2a/caption.jpg",
            height: "301",
          },
        },
        is_blessed: true,
        uploaded_date: "2022-05-04T00:21:14-0400",
        caption: "",
        id: "592413738",
        helpful_votes: "0",
        published_date: "2022-05-04T00:21:14-0400",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Manchester Places to Stay",
      ranking_position: "7",
      ranking_denominator: "361",
      ranking: "#7 Best Value of 361 places to stay in Manchester",
      distance: "1.065115814295584",
      distance_string: null,
      bearing: "west",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$95 - $104",
      hotel_class: "0.0",
      business_listings: { desktop_contacts: [], mobile_contacts: [] },
      special_offers: { desktop: [], mobile: [] },
      listing_key: "ac52c31b-5923-44fb-ab75-462ea997009a",
    },
    {
      location_id: "23313498",
      name: "Clayton House Manchester",
      latitude: "53.481686",
      longitude: "-2.172922",
      num_reviews: "0",
      timezone: "Europe/London",
      location_string: "Manchester, Greater Manchester, England",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-l/1c/f7/07/e6/6392009.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/1c/f7/07/e6/6392009.jpg",
            height: "50",
          },
          original: {
            width: "375",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1c/f7/07/e6/6392009.jpg",
            height: "500",
          },
          large: {
            width: "375",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1c/f7/07/e6/6392009.jpg",
            height: "500",
          },
          medium: {
            width: "338",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/1c/f7/07/e6/6392009.jpg",
            height: "450",
          },
        },
        is_blessed: true,
        uploaded_date: "2021-05-11T23:52:01-0400",
        caption: "Clayton House Manchester",
        id: "485951462",
        helpful_votes: "0",
        published_date: "2021-05-11T23:52:01-0400",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Manchester Places to Stay",
      ranking_position: "8",
      ranking_denominator: "361",
      ranking: "#8 Best Value of 361 places to stay in Manchester",
      distance: "1.441960865787401",
      distance_string: null,
      bearing: "northwest",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: { desktop_contacts: [], mobile_contacts: [] },
      special_offers: { desktop: [], mobile: [] },
      listing_key: "2112f805-5055-4d2e-8b49-9dd0765b8afb",
    },
    {
      location_id: "17769118",
      name: "Found Serviced Accommodation - Wandsworth Avenue",
      latitude: "53.48366",
      longitude: "-2.173095",
      num_reviews: "0",
      timezone: "Europe/London",
      location_string: "Manchester, Greater Manchester, England",
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Manchester Places to Stay",
      ranking_position: "9",
      ranking_denominator: "361",
      ranking: "#9 Best Value of 361 places to stay in Manchester",
      distance: "1.5364596543654412",
      distance_string: null,
      bearing: "northwest",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: { desktop_contacts: [], mobile_contacts: [] },
      special_offers: { desktop: [], mobile: [] },
      listing_key: "ad8fd7c0-fae1-47a8-876a-fe5919cdd922",
    },
    {
      location_id: "654717",
      name: "Clydemount Guest House",
      latitude: "53.457912",
      longitude: "-2.15845",
      num_reviews: "49",
      timezone: "Europe/London",
      location_string: "Manchester, Greater Manchester, England",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/05/f6/c8/77/stained-carpet.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/05/f6/c8/77/stained-carpet.jpg",
            height: "50",
          },
          original: {
            width: "3264",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/05/f6/c8/77/stained-carpet.jpg",
            height: "2448",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/05/f6/c8/77/stained-carpet.jpg",
            height: "412",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/05/f6/c8/77/stained-carpet.jpg",
            height: "187",
          },
        },
        is_blessed: true,
        uploaded_date: "2014-06-03T14:40:28-0400",
        caption: "Stained carpet",
        id: "100059255",
        helpful_votes: "8",
        published_date: "2014-06-06T03:24:25-0400",
        user: { user_id: null, member_id: "0", type: "user" },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Manchester Places to Stay",
      raw_ranking: "3.205388307571411",
      ranking_geo: "Manchester",
      ranking_geo_id: "187069",
      ranking_position: "10",
      ranking_denominator: "361",
      ranking_category: "bb",
      ranking: "#10 Best Value of 361 places to stay in Manchester",
      subcategory_type: "bed_and_breakfast",
      subcategory_type_label: "Bed and Breakfast",
      distance: "0.9109384907632365",
      distance_string: null,
      bearing: "southwest",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$31 - $54",
      hotel_class: "0.0",
      business_listings: { desktop_contacts: [], mobile_contacts: [] },
      special_offers: { desktop: [], mobile: [] },
      listing_key: "858c5ab4-c110-484e-b9b8-e986d94428f3",
    },
  ],
  status: {
    unfiltered_total_size: "10",
    commerce_country_iso_code: "US",
    autobroadened: true,
    progress: "100",
    auction_key: "15ef83df72f94a72af86c809028544ae",
    primary_geo: "187069",
    pricing: "base",
    doubleClickZone: "eu.uk.england.greater_manchester.manchester",
  },
  paging: { results: "10", total_results: "10" },
};
